start: count_drones nodes+ connections+

count_drones: "nb_drones:" SIGNED_INT

nodes: "start_hub:" CNAME SIGNED_INT SIGNED_INT metadata? -> start_hub
     | "end_hub:" CNAME SIGNED_INT SIGNED_INT metadata?   -> end_hub
     | "hub:" CNAME SIGNED_INT SIGNED_INT metadata?       -> hub
metadata: "[" data+ "]"

data: color | zone | max_drones
color: "color=" CNAME
zone: "zone=" CNAME
max_drones: "max_drones=" SIGNED_INT

connections: "connection:" CNAME "-" CNAME c_metadata?
c_metadata: "[" c_data "]"
c_data: "max_link_capacity=" SIGNED_INT

%import common.CNAME
%import common.SIGNED_INT
%import common.WS
%ignore WS
%ignore /#[^\r\n]*/
