start: _NEWLINE* count_drones nodes+ connections+

count_drones: "nb_drones:" SIGNED_INT _NEWLINE+

nodes: "start_hub:" HUB_NAME SIGNED_INT SIGNED_INT metadata? _NEWLINE+ -> start_hub
     | "end_hub:" HUB_NAME SIGNED_INT SIGNED_INT metadata? _NEWLINE+ -> end_hub
     | "hub:" HUB_NAME SIGNED_INT SIGNED_INT metadata? _NEWLINE+ -> hub
metadata: "[" data+ "]"

data: color | zone | max_drones
color: "color=" CNAME
zone: "zone=" CNAME
max_drones: "max_drones=" SIGNED_INT

connections: "connection:" NAME "-" NAME c_metadata? _NEWLINE+
c_metadata: "[" c_data "]"
c_data: "max_link_capacity=" SIGNED_INT

NAME: /[^\s-]+/
HUB_NAME: /\S+/

%import common.CNAME
%import common.SIGNED_INT
%import common.NEWLINE -> _NEWLINE
%import common.WS_INLINE
%ignore WS_INLINE
%ignore /#[^\r\n]*/
